### ISSUE TITLE
After 49 mail restored

### ISSUE THREAD

**Issue by ugurozturk** [evrcargo/imapsize#1]
date/time : 2017-11-05 21:31
computer name : DESKTOP-F9LJN42
user name : taran
operating system : Windows NT New build 9200
system language : Turkish
system up time : 22 hours 43 minutes
physical memory : 2048·2048 MB (free/total)
free disk space : (C:) 165,23 GB
process id : $140c
executable : imapsize.exe
exec. date/time : 2009-02-19 21:24
version : 0.3.7.0
madExcept version : 2.6a
exception class : ECacheException
exception message : Unable to perform search.

thread $4248 (TIMAPWorker):
00575cb5 imapsize.exe IMAPWorker 1132 TIMAPWorker.SearchUIDs
0057eaae imapsize.exe IMAPWorker 3126 TIMAPWorker.RestoreBackup
005728df imapsize.exe IMAPWorker 346 TIMAPWorker.Execute
00421b92 imapsize.exe madExcept 3955 HookedTThreadExecute
0043462c imapsize.exe Classes ThreadProc
00403d90 imapsize.exe System ThreadWrapper
00421b2f imapsize.exe madExcept 3942 ThreadExceptFrame
74c68652 KERNEL32.DLL BaseThreadInitThunk
>> created by main thread ($1588) at:
004bee01 imapsize.exe CustomThread 46 TCustomThread.Create

main thread ($1588):
75716a4c win32u.dll NtUserMsgWaitForMultipleObjectsEx
7527af18 user32.dll MsgWaitForMultipleObjectsEx
7527aecb user32.dll MsgWaitForMultipleObjects
0043481e imapsize.exe Classes TThread.WaitFor
00434704 imapsize.exe Classes TThread.Destroy
00572438 imapsize.exe IMAPWorker 243 TIMAPWorker.Destroy
00403070 imapsize.exe System TObject.Free
005714dd imapsize.exe ThreadManager 251 TThreadManager._removeThread
005713b9 imapsize.exe ThreadManager 220 TThreadManager.removeThread
0056b2a6 imapsize.exe RequestManager 775 TRequestManager.HandleIMAPOpOver
0056a276 imapsize.exe RequestManager 449 TRequestManager.WndProc
00468574 imapsize.exe Forms StdWndProc
752738bb user32.dll DispatchMessageA
0047112b imapsize.exe Forms TApplication.ProcessMessage
00471162 imapsize.exe Forms TApplication.HandleMessage
0047136d imapsize.exe Forms TApplication.Run
0059077f imapsize.exe imapsize 74 EntryPoint
74c68652 KERNEL32.DLL BaseThreadInitThunk

thread $3a84:
75716a4c win32u.dll NtUserMsgWaitForMultipleObjectsEx
7527af18 user32.dll MsgWaitForMultipleObjectsEx
7527aecb user32.dll MsgWaitForMultipleObjects
74c68652 KERNEL32.DLL BaseThreadInitThunk

thread $2a40 (TWorkerThread):
7728e78c ntdll.dll NtWaitForSingleObject
770aebe3 KERNELBASE.dll WaitForSingleObjectEx
770aeb3d KERNELBASE.dll WaitForSingleObject
00421b92 imapsize.exe madExcept 3955 HookedTThreadExecute
0043462c imapsize.exe Classes ThreadProc
00403d90 imapsize.exe System ThreadWrapper
00421b2f imapsize.exe madExcept 3942 ThreadExceptFrame
74c68652 KERNEL32.DLL BaseThreadInitThunk
>> created by main thread ($1588) at:
004ddf62 imapsize.exe VirtualTrees 4558 TWorkerThread.Create

thread $10c4:
772903fc ntdll.dll NtWaitForWorkViaWorkerFactory

thread $3b38:
772903fc ntdll.dll NtWaitForWorkViaWorkerFactory

thread $4338 (TVAppenderThread):
7728eaac ntdll.dll NtDelayExecution
770c2905 KERNELBASE.dll SleepEx
770c285a KERNELBASE.dll Sleep
00421b92 imapsize.exe madExcept 3955 HookedTThreadExecute
0043462c imapsize.exe Classes ThreadProc
00403d90 imapsize.exe System ThreadWrapper
00421b2f imapsize.exe madExcept 3942 ThreadExceptFrame
74c68652 KERNEL32.DLL BaseThreadInitThunk
>> created by main thread ($1588) at:
004a7d81 imapsize.exe Logging 1026 TVAppenderThread.Create

thread $2338:
772903fc ntdll.dll NtWaitForWorkViaWorkerFactory

thread $40c:
772903fc ntdll.dll NtWaitForWorkViaWorkerFactory

**Comment by vadimkim** [comment]
You are using old Delphi 6 imapsize.exe.  It doesn't run well on modern PC-s. This project is written in JAVA and has no single common source with original software. It is command-line utility that does the same job as original imapsize.exe, but better  :)
Please clone this project, install JAVA on your PC and modify run.cmd (if necessary) then choose what are you going to do (backup, restore or check)
